# fly.toml app configuration file generated for wikidiscover on 2024-07-07T09:38:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wikidiscover'
primary_region = 'mia'

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  auto_stop_delay = 43200  # 12 hours in seconds

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1