services:
  frontend:
    image: node:18.20.3-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: node:18.20.3-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm run start:dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TRANSLATE_API_URL=http://libretranslate:5000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - libretranslate

  libretranslate:
    build: ./libretranslate
    ports:
      - '5050:5000'
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,es,zh,fi,he,ru,ar,az,bg,bn,ca,cs,da
    volumes:
      - lt-local:/home/libretranslate/.local
      - lt-db:/app/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  lt-local:
  lt-db:
