services:
  frontend:
    image: node:18.20.3-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: node:18.20.3-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm run start:dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WIKIPEDIA_API_URL=https://api.wikimedia.org/wiki/Feed_API/Reference/Featured_content
      - LIBRETRANSLATE_API_URL=http://libretranslate:5000
    depends_on:
      - libretranslate

  libretranslate:
    build: ./libretranslate
    ports:
      - '5050:5000'
    environment:
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,es,zh,fi,he,ru
    volumes:
      - lt-local:/home/libretranslate/.local
      - lt-db:/app/db

volumes:
  lt-local:
  lt-db:
