export interface Language {
  name: string;
  localName: string;
  code: string;
}

export const languages: Language[] = [
  { name: 'English', localName: 'English', code: 'en' },
  { name: 'Cebuano', localName: 'Sinugboanong Binisaya', code: 'ceb' },
  { name: 'German', localName: 'Deutsch', code: 'de' },
  { name: 'French', localName: 'Français', code: 'fr' },
  { name: 'Swedish', localName: 'Svenska', code: 'sv' },
  { name: 'Dutch', localName: 'Nederlands', code: 'nl' },
  { name: 'Russian', localName: 'Русский', code: 'ru' },
  { name: 'Spanish', localName: 'Español', code: 'es' },
  { name: 'Italian', localName: 'Italiano', code: 'it' },
  { name: 'Egyptian Arabic', localName: 'مصرى (Maṣrī)', code: 'arz' },
  { name: 'Polish', localName: 'Polski', code: 'pl' },
  { name: 'Chinese', localName: '中文', code: 'zh' },
  { name: 'Japanese', localName: '日本語', code: 'ja' },
  { name: 'Ukrainian', localName: 'Українська', code: 'uk' },
  { name: 'Vietnamese', localName: 'Tiếng Việt', code: 'vi' },
  { name: 'Waray-Waray', localName: 'Winaray', code: 'war' },
  { name: 'Arabic', localName: 'العربية', code: 'ar' },
  { name: 'Portuguese', localName: 'Português', code: 'pt' },
  { name: 'Persian', localName: 'فارسی', code: 'fa' },
  { name: 'Catalan', localName: 'Català', code: 'ca' },
  { name: 'Indonesian', localName: 'Bahasa Indonesia', code: 'id' },
  { name: 'Serbian', localName: 'Српски / Srpski', code: 'sr' },
  { name: 'Korean', localName: '한국어', code: 'ko' },
  { name: 'Norwegian (Bokmål)', localName: 'Norsk (Bokmål)', code: 'no' },
  { name: 'Turkish', localName: 'Türkçe', code: 'tr' },
  { name: 'Chechen', localName: 'Нохчийн', code: 'ce' },
  { name: 'Finnish', localName: 'Suomi', code: 'fi' },
  { name: 'Czech', localName: 'Čeština', code: 'cs' },
  { name: 'Hungarian', localName: 'Magyar', code: 'hu' },
  { name: 'Tatar', localName: 'Tatarça / Татарча', code: 'tt' },
  { name: 'Romanian', localName: 'Română', code: 'ro' },
  {
    name: 'Serbo-Croatian',
    localName: 'Srpskohrvatski / Српскохрватски',
    code: 'sh',
  },
  { name: 'Basque', localName: 'Euskara', code: 'eu' },
  { name: 'Min Nan', localName: 'Bân-lâm-gú', code: 'zh-min-nan' },
  { name: 'Malay', localName: 'Bahasa Melayu', code: 'ms' },
  { name: 'Hebrew', localName: 'עברית', code: 'he' },
  { name: 'Esperanto', localName: 'Esperanto', code: 'eo' },
  { name: 'Armenian', localName: 'Հայերեն', code: 'hy' },
  { name: 'Danish', localName: 'Dansk', code: 'da' },
  { name: 'Uzbek', localName: 'O‘zbek', code: 'uz' },
  { name: 'Bulgarian', localName: 'Български', code: 'bg' },
  { name: 'Welsh', localName: 'Cymraeg', code: 'cy' },
  { name: 'Simple English', localName: 'Simple English', code: 'simple' },
  { name: 'Slovak', localName: 'Slovenčina', code: 'sk' },
  { name: 'Estonian', localName: 'Eesti', code: 'et' },
  { name: 'Belarusian', localName: 'Беларуская', code: 'be' },
  { name: 'South Azerbaijani', localName: 'تۆرکجه', code: 'azb' },
  { name: 'Greek', localName: 'Ελληνικά', code: 'el' },
  { name: 'Kazakh', localName: 'Қазақша', code: 'kk' },
  { name: 'Minangkabau', localName: 'Baso Minangkabau', code: 'min' },
  { name: 'Croatian', localName: 'Hrvatski', code: 'hr' },
  { name: 'Lithuanian', localName: 'Lietuvių', code: 'lt' },
  { name: 'Galician', localName: 'Galego', code: 'gl' },
  { name: 'Urdu', localName: 'اردو', code: 'ur' },
  { name: 'Azerbaijani', localName: 'Azərbaycanca', code: 'az' },
  { name: 'Slovenian', localName: 'Slovenščina', code: 'sl' },
  { name: 'Ladin', localName: 'Ladin', code: 'lld' },
  { name: 'Georgian', localName: 'ქართული', code: 'ka' },
  { name: 'Norwegian (Nynorsk)', localName: 'Nynorsk', code: 'nn' },
  { name: 'Tamil', localName: 'தமிழ்', code: 'ta' },
  { name: 'Thai', localName: 'ไทย', code: 'th' },
  { name: 'Hindi', localName: 'हिन्दी', code: 'hi' },
  { name: 'Bengali', localName: 'বাংলা', code: 'bn' },
  { name: 'Macedonian', localName: 'Македонски', code: 'mk' },
  { name: 'Cantonese', localName: '粵語', code: 'zh-yue' },
  { name: 'Latin', localName: 'Latina', code: 'la' },
  { name: 'Asturian', localName: 'Asturianu', code: 'ast' },
  { name: 'Latvian', localName: 'Latviešu', code: 'lv' },
  { name: 'Afrikaans', localName: 'Afrikaans', code: 'af' },
  { name: 'Tajik', localName: 'Тоҷикӣ', code: 'tg' },
  { name: 'Burmese', localName: 'မြန်မာဘာသာ', code: 'my' },
  { name: 'Albanian', localName: 'Shqip', code: 'sq' },
  { name: 'Malagasy', localName: 'Malagasy', code: 'mg' },
  { name: 'Telugu', localName: 'తెలుగు', code: 'te' },
  { name: 'Marathi', localName: 'मराठी', code: 'mr' },
  { name: 'Bosnian', localName: 'Bosanski', code: 'bs' },
  { name: 'Occitan', localName: 'Occitan', code: 'oc' },
  {
    name: 'Belarusian (Taraškievica)',
    localName: 'Беларуская (тарашкевіца)',
    code: 'be-tarask',
  },
  { name: 'Breton', localName: 'Brezhoneg', code: 'br' },
  { name: 'Malayalam', localName: 'മലയാളം', code: 'ml' },
  { name: 'Low Saxon', localName: 'Plattdüütsch', code: 'nds' },
  { name: 'Swahili', localName: 'Kiswahili', code: 'sw' },
  { name: 'Kirghiz', localName: 'Кыргызча', code: 'ky' },
  { name: 'Kurdish', localName: 'Kurdî / كوردی', code: 'ku' },
  { name: 'Lombard', localName: 'Lumbaart', code: 'lmo' },
  { name: 'Javanese', localName: 'Basa Jawa', code: 'jv' },
  {
    name: 'Western Panjabi',
    localName: 'شاہ مکھی پنجابی (Shāhmukhī Pañjābī)',
    code: 'pnb',
  },
  { name: 'Newar / Nepal Bhasa', localName: 'नेपाल भाषा', code: 'new' },
  { name: 'Haitian', localName: 'Krèyol ayisyen', code: 'ht' },
  { name: 'Venetian', localName: 'Vèneto', code: 'vec' },
  { name: 'Piedmontese', localName: 'Piemontèis', code: 'pms' },
  { name: 'Bashkir', localName: 'Башҡорт', code: 'ba' },
  { name: 'Luxembourgish', localName: 'Lëtzebuergesch', code: 'lb' },
  { name: 'Sundanese', localName: 'Basa Sunda', code: 'su' },
  { name: 'Irish', localName: 'Gaeilge', code: 'ga' },
  { name: 'Icelandic', localName: 'Íslenska', code: 'is' },
  { name: 'Silesian', localName: 'Ślůnski', code: 'szl' },
  { name: 'Chuvash', localName: 'Чăваш', code: 'cv' },
  { name: 'Sorani', localName: 'Soranî / کوردی', code: 'ckb' },
  { name: 'Punjabi', localName: 'ਪੰਜਾਬੀ', code: 'pa' },
  { name: 'West Frisian', localName: 'Frysk', code: 'fy' },
  { name: 'Ido', localName: 'Ido', code: 'io' },
  { name: 'Hausa', localName: 'هَوُسَ', code: 'ha' },
  { name: 'Tagalog', localName: 'Tagalog', code: 'tl' },
  { name: 'Aragonese', localName: 'Aragonés', code: 'an' },
  { name: 'Wu', localName: '吴语', code: 'wuu' },
  { name: 'Zazaki', localName: 'Zazaki', code: 'diq' },
  { name: 'Volapük', localName: 'Volapük', code: 'vo' },
  { name: 'Scots', localName: 'Scots', code: 'sco' },
  { name: 'Yoruba', localName: 'Yorùbá', code: 'yo' },
  { name: 'Igbo', localName: 'Igbo', code: 'ig' },
  { name: 'Kannada', localName: 'ಕನ್ನಡ', code: 'kn' },
  { name: 'Nepali', localName: 'नेपाली', code: 'ne' },
  { name: 'Mazandarani', localName: 'مَزِروني', code: 'mzn' },
  { name: 'Alemannic', localName: 'Alemannisch', code: 'als' },
  { name: 'Gujarati', localName: 'ગુજરાતી', code: 'gu' },
  { name: 'Interlingua', localName: 'Interlingua', code: 'ia' },
  { name: 'Kotava', localName: 'Kotava', code: 'avk' },
  { name: 'Crimean Tatar', localName: 'Qırımtatarca', code: 'crh' },
  { name: 'Bavarian', localName: 'Boarisch', code: 'bar' },
  { name: 'Sicilian', localName: 'Sicilianu', code: 'scn' },
  {
    name: 'Bishnupriya Manipuri',
    localName: 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী',
    code: 'bpy',
  },
  { name: 'Balinese', localName: 'Bali', code: 'ban' },
  { name: 'Quechua', localName: 'Runa Simi', code: 'qu' },
  { name: 'Mongolian', localName: 'Монгол', code: 'mn' },
  { name: 'Navajo', localName: 'Diné bizaad', code: 'nv' },
  { name: 'Mingrelian', localName: 'მარგალური (Margaluri)', code: 'xmf' },
  { name: 'Sinhalese', localName: 'සිංහල', code: 'si' },
  { name: 'Pashto', localName: 'پښتو', code: 'ps' },
  { name: 'North Frisian', localName: 'Nordfriisk', code: 'frr' },
  { name: 'Tumbuka', localName: 'chiTumbuka', code: 'tum' },
  { name: 'Ossetian', localName: 'Иронау', code: 'os' },
  { name: 'Oriya', localName: 'ଓଡ଼ିଆ', code: 'or' },
  { name: 'Sindhi', localName: 'سنڌي، سندھی ، सिन्ध', code: 'sd' },
  { name: 'Sakha', localName: 'Саха тыла (Saxa Tyla)', code: 'sah' },
  { name: 'Central Bicolano', localName: 'Bikol', code: 'bcl' },
  { name: 'Samogitian', localName: 'Žemaitėška', code: 'bat-smg' },
  { name: 'Min Dong', localName: 'Mìng-dĕ̤ng-ngṳ̄', code: 'cdo' },
  { name: 'Scottish Gaelic', localName: 'Gàidhlig', code: 'gd' },
  { name: 'Buginese', localName: 'Basa Ugi', code: 'bug' },
  { name: 'Yiddish', localName: 'ייִדיש', code: 'yi' },
  { name: 'Ilokano', localName: 'Ilokano', code: 'ilo' },
  { name: 'Amharic', localName: 'አማርኛ', code: 'am' },
  { name: 'Limburgish', localName: 'Limburgs', code: 'li' },
  { name: 'Neapolitan', localName: 'Nnapulitano', code: 'nap' },
  { name: 'Gorontalo', localName: 'Hulontalo', code: 'gor' },
  { name: 'Faroese', localName: 'Føroyskt', code: 'fo' },
  { name: 'Maithili', localName: 'मैथिली', code: 'mai' },
  { name: 'Upper Sorbian', localName: 'Hornjoserbsce', code: 'hsb' },
  { name: 'Banyumasan', localName: 'Basa Banyumasan', code: 'map-bms' },
  { name: 'Shan', localName: 'ၵႂၢမ်းတႆးလူင်', code: 'shn' },
  { name: 'Assamese', localName: 'অসমীয়া', code: 'as' },
  {
    name: 'Classical Chinese',
    localName: '古文 / 文言文',
    code: 'zh-classical',
  },
  { name: 'Emilian-Romagnol', localName: 'Emiliàn e rumagnòl', code: 'eml' },
  { name: 'Acehnese', localName: 'Bahsa Acèh', code: 'ace' },
  { name: 'Interlingue', localName: 'Interlingue', code: 'ie' },
  { name: 'Walloon', localName: 'Walon', code: 'wa' },
  { name: 'Sanskrit', localName: 'संस्कृतम्', code: 'sa' },
  { name: 'Western Armenian', localName: 'Արեւմտահայերէն', code: 'hyw' },
  { name: 'Shona', localName: 'chiShona', code: 'sn' },
  { name: 'Meadow Mari', localName: 'Олык Марий (Olyk Marij)', code: 'mhr' },
  { name: 'Zulu', localName: 'isiZulu', code: 'zu' },
  { name: 'Santali', localName: 'ᱥᱟᱱᱛᱟᱲᱤ', code: 'sat' },
  { name: 'Ligurian', localName: 'Líguru', code: 'lij' },
  { name: 'Fiji Hindi', localName: 'Fiji Hindi', code: 'hif' },
  { name: 'Banjar', localName: 'Bahasa Banjar', code: 'bjn' },
  { name: 'Khmer', localName: 'ភាសាខ្មែរ', code: 'km' },
  { name: 'Hill Mari', localName: 'Кырык Мары (Kyryk Mary)', code: 'mrj' },
  { name: 'Meitei', localName: 'ꯃꯤꯇꯩꯂꯣꯟ', code: 'mni' },
  { name: 'Hakka', localName: 'Hak-kâ-fa / 客家話', code: 'hak' },
  { name: 'Moroccan Arabic', localName: 'اللهجة المغربية', code: 'ary' },
  { name: 'Dagbani', localName: 'Dagbanli', code: 'dag' },
  { name: 'Kapampangan', localName: 'Kapampangan', code: 'pam' },
  { name: 'Tarantino', localName: 'Tarandíne', code: 'roa-tara' },
  { name: 'Rusyn', localName: 'русиньскый язык', code: 'rue' },
  { name: 'Bihari', localName: 'भोजपुरी', code: 'bh' },
  { name: 'Northern Sotho', localName: 'Sesotho sa Leboa', code: 'nso' },
  { name: 'Corsican', localName: 'Corsu', code: 'co' },
  { name: 'Somali', localName: 'Soomaaliga', code: 'so' },
  { name: 'West Flemish', localName: 'West-Vlams', code: 'vls' },
  { name: 'Dutch Low Saxon', localName: 'Nedersaksisch', code: 'nds-nl' },
  { name: 'Maori', localName: 'Māori', code: 'mi' },
  { name: 'Northern Sami', localName: 'Sámegiella', code: 'se' },
  { name: 'Erzya', localName: 'Эрзянь (Erzjanj Kelj)', code: 'myv' },
  { name: 'Talysh', localName: 'Tolışə zıvon', code: 'tly' },
  { name: 'Sardinian', localName: 'Sardu', code: 'sc' },
  { name: 'Kinyarwanda', localName: 'Ikinyarwanda', code: 'rw' },
  { name: 'Tibetan', localName: 'བོད་སྐད', code: 'bo' },
  { name: 'Cornish', localName: 'Kernewek/Karnuack', code: 'kw' },
  { name: 'Gilaki', localName: 'گیلکی', code: 'glk' },
  { name: 'Vepsian', localName: 'Vepsän', code: 'vep' },
  { name: 'Turkmen', localName: 'تركمن / Туркмен', code: 'tk' },
  { name: 'Kabyle', localName: 'Taqbaylit', code: 'kab' },
  { name: 'Manx', localName: 'Gaelg', code: 'gv' },
  { name: 'Gan', localName: '贛語', code: 'gan' },
  { name: 'Võro', localName: 'Võro', code: 'fiu-vro' },
  { name: 'Maltese', localName: 'Malti', code: 'mt' },
  { name: 'Zeelandic', localName: 'Zeêuws', code: 'zea' },
  { name: 'Abkhazian', localName: 'Аҧсуа', code: 'ab' },
  { name: 'Karakalpak', localName: 'Qaraqalpaqsha', code: 'kaa' },
  { name: 'Saraiki', localName: 'سرائیکی', code: 'skr' },
  { name: 'Uyghur', localName: 'ئۇيغۇر تىلى', code: 'ug' },
  { name: 'Inari Sami', localName: 'Anarâškielâ', code: 'smn' },
  { name: 'Franco-Provençal/Arpitan', localName: 'Arpitan', code: 'frp' },
  { name: 'Guarani', localName: "Avañe'ẽ", code: 'gn' },
  { name: 'Picard', localName: 'Picard', code: 'pcd' },
  { name: 'Moksha', localName: 'Мокшень (Mokshanj Kälj)', code: 'mdf' },
  { name: 'Udmurt', localName: 'Удмурт кыл', code: 'udm' },
  { name: 'Komi', localName: 'Коми', code: 'kv' },
  { name: 'Kashubian', localName: 'Kaszëbsczi', code: 'csb' },
  { name: 'Kashmiri', localName: 'कश्मीरी / كشميري', code: 'ks' },
  { name: 'Aymara', localName: 'Aymar', code: 'ay' },
  { name: 'Norman', localName: 'Nouormand/Normaund', code: 'nrm' },
  { name: 'Anglo-Saxon', localName: 'Englisc', code: 'ang' },
  { name: 'Lezgian', localName: 'Лезги чІал', code: 'lez' },
  { name: 'Livvi-Karelian', localName: 'livvin kieli', code: 'olo' },
  { name: 'Nahuatl', localName: 'Nāhuatl', code: 'nah' },
  {
    name: 'Lingua Franca Nova 2',
    localName: 'Lingua Franca Nova 2',
    code: 'lfn',
  },
  { name: 'Mirandese', localName: 'Mirandés', code: 'mwl' },
  { name: 'Friulian', localName: 'Furlan', code: 'fur' },
  { name: 'Saterland Frisian', localName: 'Seeltersk', code: 'stq' },
  { name: 'Papiamentu', localName: 'Papiamentu', code: 'pap' },
  { name: 'Twi', localName: 'Twi', code: 'tw' },
  { name: 'Lao', localName: 'ລາວ', code: 'lo' },
  { name: 'Lingala', localName: 'Lingala', code: 'ln' },
  { name: 'Romansh', localName: 'Rumantsch', code: 'rm' },
  { name: 'Ladino', localName: 'Dzhudezmo', code: 'lad' },
  { name: 'Extremaduran', localName: 'Estremeñu', code: 'ext' },
  {
    name: 'Goan Konkani',
    localName: 'गोंयची कोंकणी / Gõychi Konknni',
    code: 'gom',
  },
  { name: 'Doteli', localName: 'डोटेली', code: 'dty' },
  { name: 'Tuvan', localName: 'тыва дыл', code: 'tyv' },
  { name: 'Avar', localName: 'Авар', code: 'av' },
  { name: 'Komi-Permyak', localName: 'Перем Коми (Perem Komi)', code: 'koi' },
  { name: 'Lower Sorbian', localName: 'Dolnoserbski', code: 'dsb' },
  {
    name: 'Zamboanga Chavacano',
    localName: 'Chavacano de Zamboanga',
    code: 'cbk-zam',
  },
  { name: 'Luganda', localName: 'Luganda', code: 'lg' },
  { name: 'Divehi', localName: 'ދިވެހިބަސް', code: 'dv' },
  { name: 'Ripuarian', localName: 'Ripoarisch', code: 'ksh' },
  { name: 'Zhuang', localName: 'Cuengh', code: 'za' },
  { name: 'Buryat (Russia)', localName: 'Буряад', code: 'bxr' },
  { name: "Pa'O", localName: 'ပအိုဝ်ႏဘာႏသာႏ', code: 'blk' },
  { name: 'Gagauz', localName: 'Gagauz', code: 'gag' },
  { name: 'Palatinate German', localName: 'Pfälzisch', code: 'pfl' },
  { name: 'Sakizaya', localName: 'Sakizaya', code: 'szy' },
  { name: 'Hawaiian', localName: 'Hawai`i', code: 'haw' },
  { name: 'Pangasinan', localName: 'Pangasinan', code: 'pag' },
  { name: 'Atayal', localName: 'Tayal', code: 'tay' },
  { name: 'Pali', localName: 'पाऴि', code: 'pi' },
  { name: 'Betawi', localName: 'Betawi', code: 'bew' },
  { name: 'Awadhi', localName: 'ქართული', code: 'awa' },
  { name: 'Moroccan Amazigh', localName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', code: 'zgh' },
  { name: 'Fula', localName: 'Fulfulde', code: 'ff' },
  { name: 'Tulu', localName: 'ತುಳು ಭಾಷೆ', code: 'tcy' },
  { name: 'Ingush', localName: 'ГӀалгӀай', code: 'inh' },
  {
    name: 'Karachay-Balkar',
    localName: 'Къарачай-Малкъар (Qarachay-Malqar)',
    code: 'krc',
  },
  { name: 'Xhosa', localName: 'isiXhosa', code: 'xh' },
  { name: 'Atikamekw', localName: 'Atikamekw Nehiromowin', code: 'atj' },
  { name: 'Tongan', localName: 'faka Tonga', code: 'to' },
  { name: 'Pennsylvania German', localName: 'Deitsch', code: 'pdc' },
  { name: 'Mon', localName: 'ဘာသာ မန်', code: 'mnw' },
  { name: 'Aramaic', localName: 'ܐܪܡܝܐ', code: 'arc' },
  { name: 'Tachelhit', localName: 'Taclhit', code: 'shi' },
  { name: 'Oromo', localName: 'Oromoo', code: 'om' },
  { name: 'Kikuyu', localName: 'Gĩkũyũ', code: 'ki' },
  { name: 'Kalmyk', localName: 'Хальмг', code: 'xal' },
  { name: 'Tswana', localName: 'Setswana', code: 'tn' },
  { name: 'Jamaican', localName: 'Patois', code: 'jam' },
  { name: 'Nias', localName: 'Li Niha', code: 'nia' },
  { name: 'Kabiye', localName: 'Kabɩyɛ', code: 'kbp' },
  { name: 'Wolof', localName: 'Wolof', code: 'wo' },
  { name: 'Ghanaian Pidgin', localName: 'Kroo brofo', code: 'gpe' },
  { name: 'Novial', localName: 'Novial', code: 'nov' },
  { name: 'Angika', localName: 'अंगिका', code: 'anp' },
  { name: 'Fon', localName: 'fɔ̀ngbè', code: 'fon' },
  {
    name: 'Kabardian Circassian',
    localName: 'Адыгэбзэ (Adighabze)',
    code: 'kbd',
  },
  { name: 'Dagaare', localName: 'Dagaaba', code: 'dga' },
  { name: "N'Ko", localName: 'ߒߞߏ', code: 'nqo' },
  { name: 'Bislama', localName: 'Bislama', code: 'bi' },
  { name: 'Aromanian', localName: 'Armãneashce', code: 'roa-rup' },
  { name: 'Tok Pisin', localName: 'Tok Pisin', code: 'tpi' },
  { name: 'Tetum', localName: 'Tetun', code: 'tet' },
  { name: 'Lojban', localName: 'Lojban', code: 'jbo' },
  { name: 'Gun', localName: 'Gungbè', code: 'guw' },
  { name: 'Kongo', localName: 'KiKongo', code: 'kg' },
  { name: 'Fijian', localName: 'Na Vosa Vakaviti', code: 'fj' },
  { name: 'Lak', localName: 'Лакку', code: 'lbe' },
  { name: 'Old Church Slavonic', localName: 'Словѣньскъ', code: 'cu' },
  { name: 'Madurese', localName: 'Madhurâ', code: 'mad' },
  { name: 'Tahitian', localName: 'Reo Mā`ohi', code: 'ty' },
  { name: 'Nigerian Pidgin', localName: 'Naija', code: 'pcm' },
  { name: 'Seediq', localName: 'Kari Seediq', code: 'trv' },
  { name: 'Samoan', localName: 'Gagana Samoa', code: 'sm' },
  { name: 'Amis', localName: "Pangcah / 'Amis", code: 'ami' },
  { name: 'Sranan', localName: 'Sranantongo', code: 'srn' },
  { name: 'Altai', localName: 'алтай тил', code: 'alt' },
  { name: 'Tyap', localName: 'Tyap', code: 'kcg' },
  { name: 'Latgalian', localName: 'Latgaļu', code: 'ltg' },
  { name: 'Cherokee', localName: 'ᏣᎳᎩ', code: 'chr' },
  { name: 'Guianan Creole', localName: 'Kriyòl Gwiyannen', code: 'gcr' },
  { name: 'Mandailing', localName: 'Saro Mandailing', code: 'btm' },
  { name: 'Chichewa', localName: 'Chi-Chewa', code: 'ny' },
  { name: 'Sesotho', localName: 'Sesotho', code: 'st' },
  { name: 'Kusaal', localName: 'Kusaal', code: 'kus' },
  { name: 'Swati', localName: 'SiSwati', code: 'ss' },
  { name: 'Norfolk', localName: 'Norfuk', code: 'pih' },
  { name: 'Ewe', localName: 'Eʋegbe', code: 'ee' },
  { name: 'Gurenɛ', localName: 'Gurenɛ', code: 'gur' },
  { name: 'Gothic', localName: '𐌲𐌿𐍄𐌹𐍃𐌺', code: 'got' },
  { name: 'Bambara', localName: 'Bamanankan', code: 'bm' },
  { name: 'Romani', localName: 'romani - रोमानी', code: 'rmy' },
  { name: 'Venda', localName: 'Tshivenda', code: 've' },
  { name: 'Tsonga', localName: 'Xitsonga', code: 'ts' },
  { name: 'Toba Batak', localName: 'ᯅᯖᯂ᯲ ᯖᯬᯅ / Batak Toba', code: 'bbc' },
  { name: 'Cheyenne', localName: 'Tsetsêhestâhese', code: 'chy' },
  { name: 'Kirundi', localName: 'Kirundi', code: 'rn' },
  { name: 'Fante', localName: 'Mfantse', code: 'fat' },
  { name: 'Inupiak', localName: 'Iñupiak', code: 'ik' },
  { name: 'Wayuu', localName: 'wayuunaiki', code: 'guc' },
  { name: 'Adyghe', localName: 'адыгабзэ', code: 'ady' },
  { name: 'Chamorro', localName: 'Chamoru', code: 'ch' },
  { name: 'Pontic', localName: 'Ποντιακά', code: 'pnt' },
  { name: 'Igala', localName: 'Igala', code: 'igl' },
  { name: 'Central Dusun', localName: 'Kadazandusun', code: 'dtp' },
  { name: 'Inuktitut', localName: 'ᐃᓄᒃᑎᑐᑦ', code: 'iu' },
  { name: 'Paiwan', localName: 'Pinayuanan', code: 'pwn' },
  { name: 'Sango', localName: 'Sängö', code: 'sg' },
  { name: 'Dinka', localName: 'Thuɔŋjäŋ', code: 'din' },
  { name: 'Tigrinya', localName: 'ትግርኛ', code: 'ti' },
  { name: 'Dzongkha', localName: 'ཇོང་ཁ', code: 'dz' },
  { name: 'Greenlandic', localName: 'Kalaallisut', code: 'kl' },
  { name: 'Cree', localName: 'Nehiyaw', code: 'cr' },
  { name: 'Ndonga', localName: 'Oshiwambo', code: 'ng' },
  { name: 'Choctaw', localName: 'Choctaw', code: 'cho' },
  { name: 'Marshallese', localName: 'Ebon', code: 'mh' },
  { name: 'Kuanyama', localName: 'Kuanyama', code: 'kj' },
  { name: 'Sichuan Yi', localName: 'ꆇꉙ', code: 'ii' },
  { name: 'Hiri Motu', localName: 'Hiri Motu', code: 'ho' },
  { name: 'Northern Luri', localName: 'لۊری شومالی', code: 'lrc' },
  { name: 'Muscogee', localName: 'Muskogee', code: 'mus' },
  { name: 'Nauruan', localName: 'dorerin Naoero', code: 'na' },
  { name: 'Akan', localName: 'Akana', code: 'ak' },
  { name: 'Afar', localName: 'Afar', code: 'aa' },
  { name: 'Herero', localName: 'Otsiherero', code: 'hz' },
  { name: 'Kanuri', localName: 'Kanuri', code: 'kr' },
];
