export const wikipediaLanguages = [
  { name: 'Bengali', code: 'bn' },
  { name: 'German', code: 'de' },
  { name: 'Greek', code: 'el' },
  { name: 'English', code: 'en' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Latin', code: 'la' },
  { name: 'Sindhi', code: 'sd' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Chinese', code: 'zh' },
  { name: 'Bosnian', code: 'bs' },
  { name: 'Danish', code: 'da' },
  { name: 'Spanish', code: 'es' },
  { name: 'Finnish', code: 'fi' },
  { name: 'French', code: 'fr' },
  { name: 'Korean', code: 'ko' },
  { name: 'Norwegian (Bokmål)', code: 'no' },
  { name: 'Polish', code: 'pl' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Russian', code: 'ru' },
  { name: 'Scots', code: 'sco' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Arabic', code: 'ar' },
];
