name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'

      - name: Install dependencies
        run: |
          npm install
          npm run install:frontend
          npm run install:backend

      - name: Run frontend tests
        run: npm run test:frontend

      - name: Run backend tests
        run: npm run test:backend

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'

      - name: Install dependencies
        run: |
          npm install
          npm run install:frontend
          npm run install:backend

      - name: Build frontend
        run: npm run build:frontend

      - name: Build backend
        run: npm run build:backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly deploy --config frontend/fly.toml
          fly deploy --config backend/fly.toml
