name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions: write-all

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  TRANSLATE_API_URL: ${{ secrets.TRANSLATE_API_URL }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'

      - name: Install dependencies
        run: |
          npm install
          npm run install:frontend
          npm run install:backend

      - name: Create .env file for frontend
        run: npm run env:frontend

      - name: Run frontend tests
        run: npm run test:frontend
        env:
          NODE_ENV: test

      - name: Create .env file for backend
        run: npm run env:backend

      - name: Run backend tests
        run: npm run test:backend
        env:
          NODE_ENV: test

      - name: Build frontend
        run: npm run build:frontend

      - name: Build backend
        run: npm run build:backend

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create .env file for backend
        run: npm run env:backend

      - name: Deploy PROD backend to Fly.io
        run: npm run deploy:backend
        if: github.ref == 'refs/heads/main'

      - name: Deploy PREVIEW backend to Fly.io
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          path: backend
          name: pr-${{ github.event.number }}-backend-wikidiscover
        if: github.event_name == 'pull_request'

      - name: Create .env file for frontend
        run: npm run env:frontend

      - name: Deploy PROD frontend to Fly.io
        run: npm run deploy:frontend
        if: github.ref == 'refs/heads/main'

      - name: Create frontend .env with preview API URL
        run: npm run env:frontend
        env:
          VITE_API_URL: https://pr-${{ github.event.number }}-backend-wikidiscover.fly.dev
        if: github.event_name == 'pull_request'

      - name: Deploy PREVIEW frontend to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          path: frontend
          name: pr-${{ github.event.number }}-frontend-wikidiscover
        if: github.event_name == 'pull_request'

      - name: Add a message to PR with preview URLs
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const frontendUrl = `https://pr-${prNumber}-frontend-wikidiscover.fly.dev/`;
            const backendUrl = `https://pr-${prNumber}-backend-wikidiscover.fly.dev`;
            const message = `[Preview Frontend](${frontendUrl})\n[Preview Backend](${backendUrl})`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
